{{- $Values := (.helm).Values | default .Values }}
condition: '{{ true }}'
name: api-availability
rules:
- alert: SeriveApiDown
  annotations:
    description: 'API for service  "{{`{{`}} $labels.service {{`}}`}}" in cluster "{{`{{`}} $labels.cluster {{`}}`}}" is not responding for more than 5 minutes'
    summary: API unresponsive
  expr: |-
    max(probe_success) by (cluster,service) == 0
  for: 5m
  labels:
    severity: critical
  condition: '{{ true }}'
